import React,{useEffect,useMemo,useRef,useState}from "react";
import {createRoot} from "react-dom/client";
import {MapContainer,TileLayer,Marker,Popup,useMap} from "react-leaflet";
import L from "leaflet"; import {io} from "socket.io-client"; import axios from "axios"; import "./styles.css";
import "leaflet/dist/leaflet.css";

const API=import.meta.env.VITE_API_URL||"http://localhost:5000";
const icon=L.divIcon({className:"bus-pin",html:"<div>🚌</div>",iconSize:[42,42],iconAnchor:[21,21]});
function MapFly({pos}){const map=useMap();useEffect(()=>{if(pos)map.flyTo([pos.lat,pos.lng],16,{duration:1})},[pos]);return null}
function Login({onLogin}){const[email,setEmail]=useState("student@campusbus.local"),[password,setPassword]=useState("Student123!"),[err,setErr]=useState(""),[loading,setLoading]=useState(false);
 async function submit(e){e.preventDefault();setLoading(true);setErr("");try{const r=await axios.post(API+"/api/auth/login",{email,password});onLogin(r.data)}catch(e){setErr(e.response?.data?.message||"Cannot connect to backend")}finally{setLoading(false)}}
 return <div className="login-page"><div className="login-card"><div className="logo">C<span>+</span></div><h1>CampusBus</h1><p>Real-time college transport intelligence</p><form onSubmit={submit}><label>Email<input value={email} onChange={e=>setEmail(e.target.value)} /></label><label>Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} /></label>{err&&<div className="error">{err}</div>}<button disabled={loading}>{loading?"Signing in...":"Sign in"}</button></form><div className="demo"><b>Demo accounts</b><button onClick={()=>{setEmail("student@campusbus.local");setPassword("Student123!")}}>Student</button><button onClick={()=>{setEmail("driver@campusbus.local");setPassword("Driver123!")}}>Driver</button><button onClick={()=>{setEmail("admin@campusbus.local");setPassword("Admin123!")}}>Admin</button></div></div></div>}

function App(){const[sess,setSess]=useState(()=>JSON.parse(localStorage.getItem("campusbus_session")||"null"));const login=x=>{localStorage.setItem("campusbus_session",JSON.stringify(x));setSess(x)};if(!sess)return <Login onLogin={login}/>;return <Dashboard sess={sess} logout={()=>{localStorage.removeItem("campusbus_session");setSess(null)}}/>}

function Dashboard({sess,logout}){const[buses,setBuses]=useState([]),[selected,setSelected]=useState(sess.user.busId||"bus12"),[location,setLocation]=useState(null),[trip,setTrip]=useState("inactive"),[notice,setNotice]=useState("");
 const headers={Authorization:"Bearer "+sess.token}; const socket=useMemo(()=>io(API,{autoConnect:true}),[]);
 useEffect(()=>{axios.get(API+"/api/buses",{headers}).then(r=>{setBuses(r.data);const b=r.data.find(x=>x.id===selected);if(b){setTrip(b.status);setLocation(b.lastLocation)}}).catch(()=>setNotice("Backend connection unavailable."));return()=>socket.disconnect()},[]);
 useEffect(()=>{socket.emit("bus:join",selected);socket.on("location:update",x=>setLocation(x));socket.on("trip:status",x=>{if(x.busId===selected)setTrip(x.status)});return()=>{socket.off("location:update");socket.off("trip:status")}},[selected]);
 const bus=buses.find(x=>x.id===selected)||buses[0];
 const defaultPos={lat:11.0168,lng:76.9558}; const pos=location||defaultPos;
 const startTrip=async()=>{try{await axios.post(API+"/api/trips/start",{},{headers});setTrip("active")}catch(e){setNotice(e.response?.data?.message||"Unable to start trip")}};
 const stopTrip=async()=>{try{await axios.post(API+"/api/trips/stop",{},{headers});setTrip("inactive")}catch(e){setNotice("Unable to stop trip")}};
 return <div className="app"><aside><div className="brand"><div className="brandmark">C+</div><span>CampusBus</span></div><div className="profile"><div className="avatar">{sess.user.name[0]}</div><div><b>{sess.user.name}</b><small>{sess.user.role.toUpperCase()}</small></div></div><nav><a className="active">Overview</a><a>Live tracking</a><a>Routes & stops</a><a>Trip history</a>{sess.user.role==="admin"&&<a>Fleet management</a>}</nav><button className="logout" onClick={logout}>Sign out</button></aside>
 <main><header><div><p className="eyebrow">TRANSPORT OPERATIONS</p><h1>Good afternoon, {sess.user.name.split(" ")[0]}.</h1></div><div className="live"><span className={trip==="active"?"dot on":"dot"}></span>{trip==="active"?"LIVE SYSTEM":"SYSTEM READY"}</div></header>
 {notice&&<div className="notice">{notice}</div>}
 <section className="metrics"><Metric label="Assigned bus" value={bus?.name||"Loading"} icon="🚌"/><Metric label="Trip status" value={trip==="active"?"On route":"Inactive"} icon={trip==="active"?"●":"○"}/><Metric label="GPS feed" value={location?"Connected":"Waiting"} icon="◉"/><Metric label="Last update" value={location?new Date(location.updatedAt).toLocaleTimeString():"—"} icon="◷"/></section>
 <section className="content-grid"><div className="map-panel"><div className="panel-head"><div><h2>Live vehicle location</h2><p>{bus?.route||"Loading route"}</p></div><select value={selected} onChange={e=>setSelected(e.target.value)}>{buses.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></div><div className="map-wrap"><MapContainer center={[pos.lat,pos.lng]} zoom={14} scrollWheelZoom style={{height:"100%",width:"100%"}}><TileLayer attribution='© OpenStreetMap contributors' url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"/><MapFly pos={pos}/>{location&&<Marker position={[pos.lat,pos.lng]} icon={icon}><Popup><b>{bus?.name}</b><br/>Live GPS location<br/>Accuracy: {Math.round(location.accuracy||0)} m</Popup></Marker>}</MapContainer>{!location&&<div className="map-empty">Waiting for the driver's real GPS location…</div>}</div><div className="location-bar"><span>Latitude <b>{location?pos.lat.toFixed(6):"—"}</b></span><span>Longitude <b>{location?pos.lng.toFixed(6):"—"}</b></span><span>Accuracy <b>{location?Math.round(location.accuracy||0)+" m":"—"}</b></span></div></div>
 <div className="side-panels"><div className="panel route"><h2>Route progress</h2><div className="route-line">{(bus?.stops||[]).map((s,i)=><div className={i===0?"done":""} key={s}><span>{i+1}</span><p>{s}</p></div>)}</div></div>{sess.user.role==="driver"?<DriverControls token={sess.token} busId={sess.user.busId} socket={socket} trip={trip} startTrip={startTrip} stopTrip={stopTrip}/>:<div className="panel"><h2>Service information</h2><p className="muted">The bus marker appears only when the driver starts a trip and shares actual GPS location.</p><div className="info"><span>Tracking mode</span><b>Real-time Socket.IO</b></div><div className="info"><span>Map provider</span><b>OpenStreetMap</b></div></div>}</div></section>
 {sess.user.role==="admin"&&<Admin buses={buses}/>}
 </main></div>}
function Metric({label,value,icon}){return <div className="metric"><div className="metric-icon">{icon}</div><div><small>{label}</small><h3>{value}</h3></div></div>}
function DriverControls({busId,socket,trip,startTrip,stopTrip}){const watch=useRef(null),[gps,setGps]=useState("Not sharing"),[err,setErr]=useState("");
 function begin(){if(!navigator.geolocation){setErr("This browser does not support geolocation.");return}startTrip();setErr("");watch.current=navigator.geolocation.watchPosition(p=>{const x={busId,lat:p.coords.latitude,lng:p.coords.longitude,accuracy:p.coords.accuracy,speed:p.coords.speed,heading:p.coords.heading};socket.emit("location:update",x);setGps("Sharing live GPS")},e=>setErr(e.message),{enableHighAccuracy:true,maximumAge:5000,timeout:15000})}
 function end(){if(watch.current!==null)navigator.geolocation.clearWatch(watch.current);watch.current=null;setGps("Not sharing");stopTrip()}
 return <div className="panel driver"><h2>Driver control</h2><p className="muted">Use this on the driver's phone and allow location access.</p><div className={gps.includes("Sharing")?"gps good":"gps"}>● {gps}</div>{err&&<div className="error">{err}</div>}{trip==="active"?<button className="danger-btn" onClick={end}>Stop trip & GPS</button>:<button className="primary-btn" onClick={begin}>Start trip & share GPS</button>}<small>For a real phone outside localhost, deploy with HTTPS.</small></div>}
function Admin({buses}){return <section className="admin-section"><h2>Fleet overview</h2><div className="fleet">{buses.map(b=><div className="fleet-row" key={b.id}><b>{b.name}</b><span>{b.route}</span><span className={b.status==="active"?"status active":"status"}>{b.status}</span></div>)}</div></section>}
createRoot(document.getElementById("root")).render(<App/>);